### PR TITLE
feat(babel-sugar-inject-h): `setup` method support

### PR DESCRIPTION
**Pull request by u3u**
refer: https://github.com/vuejs/vue-function-api/issues/64

### CODE REVIEW

**Comment by u3u** [comment]
@sodatea Do you have any thoughts?

**Comment by haoqunjiang** [comment]
I don't think this repository is the best place to provide this utility.
`vue-function-api` is an experimental plugin. Its API is still subject to change as the discussion of the RFC moves along. So I recommend you to ship a standalone babel plugin for `setup` support, and then point to that package in the `vue-function-api` repository for those who do need it.

**Comment by u3u** [comment]
Well, but can not get `this` in the `setup` method, so will cause an exception. Should I skip it?

**Comment by luwanquan** [comment]
I wrote a babel plugin to solve this problem, see [babel-preset-vca-jsx](https://github.com/luwanquan/babel-preset-vca-jsx).

**Comment by haoqunjiang** [comment]
As `@vue/composition-api` is preparing for a v1 release (https://github.com/vuejs/composition-api/pull/390), I think now is a good time to have first-class support for this usage.

If anyone's interested, would you please open a new PR based on the latest version of `@vue/composition-api`?
I would love to do this myself but I haven't got the time, so any help is appreciated.

Cc: @antfu

**Comment by haoqunjiang** [comment]
Closing as #142 has been merged and released in v1.2.1.

**Pull request closed without merging**
