### PR TITLE
feat: allow prior babel plugins to traverse JSX tree thoroughly

### LINKED ISSUE #86: Replace JSXElement node on 'exit' instead of 'enter'.
Current [behavior] of this plugin is replacing the entire JSXElement node, along with its children, on `enter` phase, which hinders other plugins from visiting decendants of that JSXElement recursively.

## Usecase:
Suppose that a plugin `foo` is to collect thrid party component references in every file and then emit a file that imports and globally registeres all used components (common practice when the third party library provides tons of components but only a few of them is of interest). 

## Problem: 
With this (referring to @vue/babel-plugin-transform-vue-jsx) plugin applied, `foo` can only visit the root JSXElement and all of its children would not be visited because they would have been replaced with normal `h` call by this plugin. Indeed, author of `foo` can traverse the children of root JSXElement by himself/herself but that would be duplicating the visitor pattern provided by babel. 

## Solution:
Changing this plugin's visitor to replace the original jsx node on `exit` phase would make other plugins (which are, by assumption, applied prior to this plugin) have a chance to recursively visit all the jsx nodes, without affecting the original behavior of this plugin.

## Reference:
Both [babel-plugin-jsx] and [babel-plugin-transform-react-jsx](which inherits the former) are applying the actual transformation on `exit` phase.

[behavior]: https://github.com/vuejs/jsx/blob/67d6d39beab9f853118b4e0bbe901f5899ae7245/packages/babel-plugin-transform-vue-jsx/src/index.js#L455
[babel-plugin-jsx]: https://github.com/OpenJSX/babel-plugin-jsx
[babel-plugin-transform-react-jsx]: https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-jsx/README.md

### PR DESCRIPTION
**Pull request by nandin-borjigin**
close #86

### CODE REVIEW

**Comment by nandin-borjigin** [comment]
@sodatea Any thoughts?

**Comment by nickmessing** [comment]
@Nandiin, nice PR, good idea, but with this PR it makes sense to change all sugar plugins to work without pre-traversing the Program, do you want to include that?

**Comment by nandin-borjigin** [comment]
I'm happy to do that~ I'll make a PR later, after work, today.

Sorry for the late reply.

**Review by nickmessing — APPROVED** [review]

**Comment by haoqunjiang** [comment]
This change breaks `functional-vue` and `inject-h` because it would fail the `hasJSX()` check.
I'll revert the two packages as a quick fix for now.

**Comment by haoqunjiang** [comment]
The change in `v-model` & `v-on` plugin needs to be reverted too, because they need to apply before `arrow-functions` to get the correct `this` scope.

**Pull request merged**
